version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable   # CircleCI base image with Docker support
    steps:
      - checkout

      # Enable Docker inside CircleCI
      - setup_remote_docker:
          version: 20.10.14

      # Log in to DockerHub using environment variables
      - run:
          name: Log in to DockerHub
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # Build and push Docker image
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/flask-ci-cd:latest .
            docker tag $DOCKERHUB_USERNAME/flask-ci-cd:latest $DOCKERHUB_USERNAME/flask-ci-cd:${CIRCLE_SHA1}
            docker push $DOCKERHUB_USERNAME/flask-ci-cd:latest
            docker push $DOCKERHUB_USERNAME/flask-ci-cd:${CIRCLE_SHA1}

workflows:
  version: 2
  docker-build-push:
    jobs:
      - build-and-push
